publish to pypi:
  type: deploy
  script:
    - python -m pip install twine wheel
    - python setup.py sdist bdist_wheel
    - twine upload -u $PYPI_USER -p $PYPI_PASSWORD dist/*
  tags:
    - python3.4
  only:
    - /^v[\d\.]+.*$/
  allow_failure: true
